name: vendor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_phoenix: ^1.1.1
  percent_indicator: ^4.2.3
  flutter_bloc: ^8.1.5
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.3
  shared_preferences: ^2.2.3
  toast: ^0.3.0
  image_picker: ^1.0.1
  shimmer_animation: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  flutter_barcode_scanner:
    git:
      url: https://github.com/TECMANIC/flutter_barcode_scanner.git
      ref: master
  google_place: ^0.4.7
  mapbox_search: ^4.2.2
  esc_pos_bluetooth:
    git:
      url: https://github.com/TECMANIC/flutter_esc_pos_bluetooth.git
      ref: main
  permission_handler: ^11.3.1
  esc_pos_utils: ^1.1.0
  awesome_notifications: ^0.8.3
  flutter_image_compress: ^2.3.0
  firebase_storage: ^11.7.6
  cloud_firestore: ^4.17.4
  image_cropper: ^6.0.0
  dio: ^5.4.3+1

  http: any
  path_provider: any
  collection: any
  intl: any
  image: any
dependency_overrides:
#  intl: ^0.18.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
#  esc_pos_printer: ^4.0.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf

  assets:
    - assets/
    - assets/Logos/
    - assets/ProductImages/
